packages:
  - apps/*

overrides:
  "@angular-devkit/core>ajv": 8.18.0
  "@angular-devkit/core>picomatch": 4.0.4
  "@nestjs/swagger>js-yaml": 5.2.2
  "@redocly/openapi-core>js-yaml": 4.3.1
  find-my-way: 9.7.0

publicHoistPattern:
  - "*@heroui/*"

strictPeerDependencies: false
confirmModulesPurge: false

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": false
  prisma: true
  sharp: true
  unrs-resolver: true
