packages:
  - apps/*

publicHoistPattern:
  - "*@heroui/*"

strictPeerDependencies: false
confirmModulesPurge: false

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": false
  prisma: true
  sharp: true
  unrs-resolver: true
