/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Comprueba que el proceso del API está activo */
    get: operations["HealthController_live"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Comprueba que PostgreSQL está disponible */
    get: operations["HealthController_ready"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/home": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devuelve portada, estrenos y añadidos recientes */
    get: operations["HomeController_getHome"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Busca y filtra el catálogo paginado */
    get: operations["CatalogController_getCatalog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devuelve hasta ocho sugerencias de búsqueda */
    get: operations["CatalogController_getSuggestions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anime/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devuelve la ficha normalizada de un anime */
    get: operations["AnimeController_getAnime"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anime/{slug}/episodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devuelve episodios en páginas de cincuenta */
    get: operations["AnimeController_getEpisodes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/schedule": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devuelve el horario semanal estimado */
    get: operations["ScheduleController_getSchedule"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anime/{slug}/downloads/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resuelve hasta cincuenta episodios por operación */
    post: operations["DownloadController_resolve"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/anime/{slug}/download-jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Crea un trabajo durable para una serie o rango */
    post: operations["DownloadJobsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/download-jobs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulta progreso y resultados mediante capacidad */
    get: operations["DownloadJobsController_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/download-jobs/{id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reintenta únicamente episodios fallidos */
    post: operations["DownloadJobsController_retry"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/download-jobs/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancela los ítems pendientes del trabajo */
    post: operations["DownloadJobsController_cancel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CategoryDto: {
      id: string;
      name: string;
      slug: string;
    };
    AnimeSummaryDto: {
      id: string;
      slug: string;
      title: string;
      synopsis?: string | null;
      posterUrl?: string | null;
      backdropUrl?: string | null;
      category?: components["schemas"]["CategoryDto"] | null;
      /** @enum {string} */
      status: "UNKNOWN" | "AIRING" | "FINISHED" | "UPCOMING";
      startDate?: string | null;
      mature: boolean;
    };
    EpisodeDto: {
      id: string;
      number: number;
      title?: string | null;
      imageUrl?: string | null;
      publishedAt?: string | null;
    };
    RecentEpisodeDto: {
      anime: components["schemas"]["AnimeSummaryDto"];
      episode: components["schemas"]["EpisodeDto"];
    };
    HomeDataDto: {
      featured: components["schemas"]["AnimeSummaryDto"][];
      recentEpisodes: components["schemas"]["RecentEpisodeDto"][];
      recentAnime: components["schemas"]["AnimeSummaryDto"][];
    };
    FreshnessDto: {
      fetchedAt: string;
      nextRefreshAt: string;
      stale: boolean;
    };
    HomeResponseDto: {
      data: components["schemas"]["HomeDataDto"];
      meta: components["schemas"]["FreshnessDto"];
    };
    CatalogMetaDto: {
      fetchedAt: string;
      nextRefreshAt: string;
      stale: boolean;
      page: number;
      perPage: number;
      totalPages: number;
      totalRecords: number;
      categories: components["schemas"]["CategoryDto"][];
      genres: components["schemas"]["CategoryDto"][];
      years: number[];
    };
    CatalogResponseDto: {
      data: components["schemas"]["AnimeSummaryDto"][];
      meta: components["schemas"]["CatalogMetaDto"];
    };
    SuggestionResponseDto: {
      data: components["schemas"]["AnimeSummaryDto"][];
    };
    RelationDto: {
      /** @enum {string} */
      kind:
        | "PREQUEL"
        | "SEQUEL"
        | "MAIN_STORY"
        | "SIDE_STORY"
        | "SUMMARY"
        | "ALTERNATIVE"
        | "OTHER";
      anime: components["schemas"]["AnimeSummaryDto"];
      position: number;
    };
    AnimeDetailDto: {
      id: string;
      slug: string;
      title: string;
      synopsis?: string | null;
      posterUrl?: string | null;
      backdropUrl?: string | null;
      category?: components["schemas"]["CategoryDto"] | null;
      /** @enum {string} */
      status: "UNKNOWN" | "AIRING" | "FINISHED" | "UPCOMING";
      startDate?: string | null;
      mature: boolean;
      alternativeTitle?: string | null;
      trailerUrl?: string | null;
      endDate?: string | null;
      nextEpisodeAt?: string | null;
      episodeCount?: number | null;
      score?: number | null;
      votes?: number | null;
      sourceUrl: string;
      genres: components["schemas"]["CategoryDto"][];
      relations: components["schemas"]["RelationDto"][];
    };
    AnimeResponseDto: {
      data: components["schemas"]["AnimeDetailDto"];
      meta: components["schemas"]["FreshnessDto"];
    };
    EpisodePageMetaDto: {
      page: number;
      perPage: number;
      totalPages: number;
      totalRecords: number;
    };
    EpisodePageResponseDto: {
      data: components["schemas"]["EpisodeDto"][];
      meta: components["schemas"]["EpisodePageMetaDto"];
    };
    ScheduleEntryDto: {
      anime: components["schemas"]["AnimeSummaryDto"];
      latestEpisode: components["schemas"]["EpisodeDto"];
      basisPublishedAt: string;
    };
    ScheduleResponseDto: {
      data: components["schemas"]["ScheduleEntryDto"][];
      meta: components["schemas"]["FreshnessDto"];
    };
    ResolveDownloadsDto: {
      episodeNumbers: number[];
      /** @enum {string} */
      audio: "SUB" | "DUB";
      providers: ("MEGA" | "PIXELDRAIN" | "MP4UPLOAD" | "ONE_FICHIER")[];
      /** @default false */
      refresh: boolean;
    };
    ResolvedLinkDto: {
      /** @enum {string} */
      provider: "MEGA" | "PIXELDRAIN" | "MP4UPLOAD" | "ONE_FICHIER";
      url: string;
    };
    ResolvedEpisodeDto: {
      episodeNumber: number;
      /** @enum {string} */
      audio: "SUB" | "DUB";
      links: components["schemas"]["ResolvedLinkDto"][];
      errorCode?: string | null;
    };
    ResolveDownloadsDataDto: {
      packageName: string;
      episodes: components["schemas"]["ResolvedEpisodeDto"][];
    };
    ResolveDownloadsResponseDto: {
      data: components["schemas"]["ResolveDownloadsDataDto"];
    };
    CreateDownloadJobDto: {
      /** @enum {string} */
      scope: "ALL" | "RANGE";
      /** @enum {string} */
      audio: "SUB" | "DUB";
      providers: ("MEGA" | "PIXELDRAIN" | "MP4UPLOAD" | "ONE_FICHIER")[];
      from?: number;
      to?: number;
    };
    DownloadJobReceiptDto: {
      jobId: string;
      accessToken: string;
      expiresAt: string;
    };
    DownloadJobReceiptResponseDto: {
      data: components["schemas"]["DownloadJobReceiptDto"];
    };
    DownloadJobDataDto: {
      id: string;
      /** @enum {string} */
      status:
        "QUEUED" | "RUNNING" | "COMPLETED" | "PARTIAL" | "FAILED" | "CANCELLED";
      packageName: string;
      totalItems: number;
      completedItems: number;
      failedItems: number;
      expiresAt: string;
      episodes: components["schemas"]["ResolvedEpisodeDto"][];
    };
    DownloadJobResponseDto: {
      data: components["schemas"]["DownloadJobDataDto"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HomeController_getHome: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HomeResponseDto"];
        };
      };
    };
  };
  CatalogController_getCatalog: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogResponseDto"];
        };
      };
    };
  };
  CatalogController_getSuggestions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuggestionResponseDto"];
        };
      };
    };
  };
  AnimeController_getAnime: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnimeResponseDto"];
        };
      };
    };
  };
  AnimeController_getEpisodes: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodePageResponseDto"];
        };
      };
    };
  };
  ScheduleController_getSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScheduleResponseDto"];
        };
      };
    };
  };
  DownloadController_resolve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveDownloadsDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResolveDownloadsResponseDto"];
        };
      };
    };
  };
  DownloadJobsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDownloadJobDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DownloadJobReceiptResponseDto"];
        };
      };
    };
  };
  DownloadJobsController_get: {
    parameters: {
      query?: never;
      header: {
        authorization: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DownloadJobResponseDto"];
        };
      };
    };
  };
  DownloadJobsController_retry: {
    parameters: {
      query?: never;
      header: {
        authorization: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DownloadJobResponseDto"];
        };
      };
    };
  };
  DownloadJobsController_cancel: {
    parameters: {
      query?: never;
      header: {
        authorization: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DownloadJobResponseDto"];
        };
      };
    };
  };
}
